// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABq7bwxaW6Q77HwpFVyEGf_TNHX5tmVm8',
    appId: '1:50112590303:web:bb402304c91a3bb206d46a',
    messagingSenderId: '50112590303',
    projectId: 'driveapp-b55c3',
    authDomain: 'driveapp-b55c3.firebaseapp.com',
    storageBucket: 'driveapp-b55c3.firebasestorage.app',
    measurementId: 'G-0MWYGX61V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgArS56jH187H6AmgKy5GAsSNhcJEabSQ',
    appId: '1:50112590303:android:4d180037c5a63c6b06d46a',
    messagingSenderId: '50112590303',
    projectId: 'driveapp-b55c3',
    storageBucket: 'driveapp-b55c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAehNkvbi9HFSqATrnNvi6TqKAJqJT8EVw',
    appId: '1:50112590303:ios:38e7e00a80fbd56306d46a',
    messagingSenderId: '50112590303',
    projectId: 'driveapp-b55c3',
    storageBucket: 'driveapp-b55c3.firebasestorage.app',
    iosBundleId: 'com.example.driveAppDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAehNkvbi9HFSqATrnNvi6TqKAJqJT8EVw',
    appId: '1:50112590303:ios:38e7e00a80fbd56306d46a',
    messagingSenderId: '50112590303',
    projectId: 'driveapp-b55c3',
    storageBucket: 'driveapp-b55c3.firebasestorage.app',
    iosBundleId: 'com.example.driveAppDart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABq7bwxaW6Q77HwpFVyEGf_TNHX5tmVm8',
    appId: '1:50112590303:web:769f0fb42b3a646006d46a',
    messagingSenderId: '50112590303',
    projectId: 'driveapp-b55c3',
    authDomain: 'driveapp-b55c3.firebaseapp.com',
    storageBucket: 'driveapp-b55c3.firebasestorage.app',
    measurementId: 'G-NNP3VNL8S0',
  );
}
